# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags:
      - "v*.*.*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get tags
        id: get_tags
        run: |
          vX_X_X=$(echo $GITHUB_REF | sed 's/^refs\/tags\/v\(\(\(.*\)\..*\)\..*\)$/\3/')
          vX_X=$(echo $GITHUB_REF | sed 's/^refs\/tags\/v\(\(\(.*\)\..*\)\..*\)$/\2/')
          vX=$(echo $GITHUB_REF | sed 's/^refs\/tags\/v\(\(\(.*\)\..*\)\..*\)$/\1/')

          echo ::set-output name=tags::$(
            echo $(
              for tag in latest $vX_X_X $vX_X $vX; do
                echo ${{ secrets.DOCKER_HUB_USERNAME }}/docker-service-index:$tag
              done
            ) | sed 's/ /,/g'
          )

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ steps.get_tags.outputs.tags }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
